import * as THREE from "./vendor/three.module.min.js";
import { CHARACTERS, avatarStyle } from "./characters.js";
import { Store } from "./store.js";

const $=s=>document.querySelector(s), statusEl=$("#status"), spinButton=$("#spin"), soundButton=$("#sound"), exitButton=$("#exit"), collectionButton=$("#collectionButton"), reveal=$("#reveal"), collection=$("#collection");
const embedded=self!==top, THEME="./assets/audio/glitch-park-theme.mp3";
let soundEnabled=true, themeAudio, audioContext, phase="waiting", phaseTime=0, results=[0,0,0], targets=[0,0,0], stopped=[false,false,false], nextTick=[0,0,0], look={x:0,y:0,tx:0,ty:0};
Store.load();

function requestTheme(action,muted=false){
  if(embedded){ parent.postMessage({type:"glitch-park:music",action,track:"theme",url:new URL(THEME,location.href).href,muted},"*"); return; }
  themeAudio||=Object.assign(new Audio(THEME),{loop:true,volume:.27}); themeAudio.muted=muted;
  if(action==="play"&&!muted) themeAudio.play().catch(()=>{}); if(action==="pause") themeAudio.pause();
}
if(embedded){exitButton.hidden=false;exitButton.onclick=()=>parent.postMessage({type:"slots:exit"},"*");}
else requestTheme("play");
function beep(freq=440,duration=.08,volume=.035,type="sine"){
  if(!soundEnabled)return; audioContext||=new(window.AudioContext||window.webkitAudioContext)(); const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);
}
soundButton.onclick=()=>{soundEnabled=!soundEnabled;soundButton.textContent=`聲音：${soundEnabled?"開":"關"}`;soundButton.setAttribute("aria-pressed",String(!soundEnabled));requestTheme("mute",!soundEnabled);if(soundEnabled){requestTheme("play");beep(660);}};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x10091d);scene.fog=new THREE.Fog(0x10091d,9,24);
const camera=new THREE.PerspectiveCamera(40,1,.1,50),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;document.body.prepend(renderer.domElement);
const mat=(color,rough=.45,metal=.05,emissive=0,intensity=0)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:intensity});
const box=(w,h,d,m,x,y,z,p=scene)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o};
scene.add(new THREE.HemisphereLight(0x7562a2,0x160d24,1.8));const key=new THREE.SpotLight(0xd7ccff,24,14,.58,.55,1.7);key.position.set(2,7,6);key.target.position.set(0,2,0);key.castShadow=true;scene.add(key,key.target);
for(const [x,c] of [[-3,0x69eee0],[3,0xff69c3]]){const p=new THREE.PointLight(c,8,7,2);p.position.set(x,2,1);scene.add(p)}
const floor=box(18,.12,18,mat(0x171022,.62),0,-.08,0);const grid=new THREE.GridHelper(18,18,0x5d3d8d,0x2a1a43);grid.position.y=.001;scene.add(grid);
box(18,9,.15,mat(0x1c102c,.8),0,4,-5.2);for(let x=-7;x<=7;x+=2){box(.055,7,.03,mat(0x69eee0,.35,0,0x69eee0,2.5),x,3.5,-5.08);}
const machine=new THREE.Group();scene.add(machine);box(4.65,5.55,2.3,mat(0x392458,.3,.34),0,2.78,0,machine);box(4.32,1.05,.16,mat(0x20122e,.25,.1,0xff72c5,2.7),0,5.08,1.2,machine);box(4.02,.76,.08,mat(0x171022,.3,.1),0,5.08,1.31,machine);
const signCanvas=document.createElement("canvas");signCanvas.width=900;signCanvas.height=180;const sx=signCanvas.getContext("2d");sx.fillStyle="#211333";sx.fillRect(0,0,900,180);sx.strokeStyle="#69eee0";sx.lineWidth=12;sx.strokeRect(10,10,880,160);sx.textAlign="center";sx.fillStyle="#ffd36e";sx.font="900 86px system-ui";sx.fillText("GLITCH 777",450,108);sx.fillStyle="#f8f4ff";sx.font="500 24px system-ui";sx.fillText("格莉奇遊樂園・幸運拉霸",450,148);const signTex=new THREE.CanvasTexture(signCanvas);signTex.colorSpace=THREE.SRGBColorSpace;const sign=new THREE.Mesh(new THREE.PlaneGeometry(3.9,.78),new THREE.MeshBasicMaterial({map:signTex,toneMapped:false}));sign.position.set(0,5.08,1.405);machine.add(sign);
box(3.95,2.08,.3,mat(0x110a1c,.28,.2),0,3.45,1.18,machine);const atlas=await new THREE.TextureLoader().loadAsync("./assets/avatar-atlas.webp");atlas.colorSpace=THREE.SRGBColorSpace;atlas.wrapS=atlas.wrapT=THREE.RepeatWrapping;
function reelMaterial(index){const map=atlas.clone();map.needsUpdate=true;map.repeat.set(.25,.5);const m=new THREE.MeshBasicMaterial({map,toneMapped:false});setSymbol({material:m},index);return m}
function setSymbol(reel,index){const map=reel.material.map,col=index%4,row=Math.floor(index/4);map.offset.set(col*.25,row?0:.5);map.needsUpdate=true;results[reels.indexOf(reel)]=index;}
const reels=[];for(let i=0;i<3;i++){const x=(i-1)*1.18;box(1.02,1.64,.12,mat(0xf5efff,.34),x,3.45,1.38,machine);const reel=new THREE.Mesh(new THREE.PlaneGeometry(.9,.9),reelMaterial(i));reel.position.set(x,3.45,1.465);machine.add(reel);reels.push(reel)}
const coin=box(.58,.82,.13,mat(0x171022,.25,.5),-1.5,1.62,1.22,machine);coin.userData.action="coin";box(.1,.48,.04,mat(0xffd36e,.2,.5,0xffd36e,3),-1.5,1.62,1.31,machine);
const lever=new THREE.Group();lever.position.set(2.66,2.65,.35);machine.add(lever);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,1.45,14),mat(0xe9e6f0,.18,.75));stem.position.y=.62;lever.add(stem);const knob=new THREE.Mesh(new THREE.SphereGeometry(.27,24,18),mat(0xff6dbd,.22,.25,0xff6dbd,1.2));knob.position.y=1.35;lever.add(knob);knob.userData.action=stem.userData.action="spin";
box(4.2,.58,1.75,mat(0x211331,.3,.25,0x6943a2,.7),0,.28,.15,machine);for(const [i,x] of [-1.7,-1.14,-.57,0,.57,1.14,1.7].entries()){const color=i%2?0xff72c5:0x69eee0;box(.1,i%3===1?.72:1.02,.08,mat(color,.2,.2,color,3),x,.92,1.2,machine)}

function resize(){const w=innerWidth,h=innerHeight,tall=h/w>1.22;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=tall?47:38;camera.position.set(0,tall?3.15:3.08,tall?10.1:9.8);camera.lookAt(0,tall?2.65:2.72,.1);camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener("pointerdown",e=>{requestTheme("play",!soundEnabled);pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(machine.children,true).find(h=>h.object.userData.action);if(hit?.object.userData.action==="coin")insertCoin();if(hit?.object.userData.action==="spin")spin();});renderer.domElement.addEventListener("pointermove",e=>{if(phase!=="waiting")return;look.tx=e.clientX/innerWidth*2-1;look.ty=e.clientY/innerHeight*2-1});
function insertCoin(){if(phase!=="waiting")return;phase="ready";statusEl.innerHTML="代幣投入完成，<b>拉下右側把手</b>。";spinButton.textContent="拉下把手";beep(720,.08,.05,"square");}
function spin(){if(phase==="waiting"){insertCoin();return}if(phase!=="ready")return;phase="spinning";phaseTime=0;stopped=[false,false,false];nextTick=[0,0,0];const hero=Math.floor(Math.random()*7),jackpot=Math.random()<.23;targets=jackpot?[hero,hero,hero]:[Math.floor(Math.random()*7),hero,Math.floor(Math.random()*7)];if(!jackpot&&targets[0]===hero&&targets[2]===hero)targets[2]=(hero+1)%7;statusEl.textContent="轉輪正在尋找今天的幸運角色……";spinButton.disabled=true;lever.rotation.z=-.52;beep(150,.3,.04,"sawtooth");}
spinButton.onclick=()=>phase==="waiting"?insertCoin():spin();addEventListener("keydown",e=>{if(e.key==="c"||e.key==="C")insertCoin();if(e.code==="Space"){e.preventDefault();phase==="waiting"?insertCoin():spin();}});
function finish(){const jackpot=targets.every(v=>v===targets[0]),hero=CHARACTERS[targets[1]];Store.finish(hero.id,jackpot);renderCollection();statusEl.innerHTML=jackpot?`<b>777 JACKPOT！</b>${hero.name} 已加入收藏。`:`本局幸運角色是 <b>${hero.name}</b>。`;reveal.innerHTML=`<div class="card"><div class="eyebrow">${jackpot?"777 JACKPOT":"本局幸運角色"}</div><div class="bigAvatar"><span class="avatar" style="${avatarStyle(targets[1])}"></span></div><h2>${hero.name}</h2><p>「${hero.line}」</p><button>再玩一次</button></div>`;reveal.hidden=false;reveal.querySelector("button").onclick=reset;if(jackpot){[523,659,784].forEach((f,i)=>setTimeout(()=>beep(f,.22,.06),i*120))}else beep(520,.18,.045);phase="showing";}
function reset(){reveal.hidden=true;phase="waiting";phaseTime=0;spinButton.disabled=false;spinButton.textContent="投幣";statusEl.textContent="請先投入代幣。";lever.rotation.z=0;}
function renderCollection(){collectionButton.innerHTML=CHARACTERS.map((c,i)=>Store.data.owned.includes(c.id)?`<span class="slot has"><span class="avatar" style="${avatarStyle(i)}"></span></span>`:`<span class="slot">？</span>`).join("")}
function openCollection(){collection.innerHTML=`<div class="card"><div class="collectionHead"><span>777 中獎收藏（${Store.data.owned.length}/7）</span><button>關閉</button></div>${CHARACTERS.map((c,i)=>`<div class="row"><span class="mini"><span class="avatar" style="${avatarStyle(i)}"></span></span><div><b>${c.name}</b><br><small>${Store.data.owned.includes(c.id)?"JACKPOT 已收藏":"尚未轉到三個相同圖案"}</small></div></div>`).join("")}</div>`;collection.hidden=false;collection.querySelector("button").onclick=()=>collection.hidden=true}
collectionButton.onclick=openCollection;collectionButton.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openCollection()}};renderCollection();
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;phaseTime+=dt;if(phase==="spinning"){for(let i=0;i<3;i++){if(stopped[i])continue;if(phaseTime>nextTick[i]){setSymbol(reels[i],(results[i]+1)%7);nextTick[i]=phaseTime+.065;beep(185+i*35,.025,.012,"square")}if(phaseTime>1.25+i*.52){setSymbol(reels[i],targets[i]);stopped[i]=true;beep(360+i*120,.12,.04,"triangle")}}if(stopped.every(Boolean)){phase="settling";setTimeout(finish,260)}}look.x+=(look.tx-look.x)*Math.min(dt*2.5,1);look.y+=(look.ty-look.y)*Math.min(dt*2.5,1);if(phase==="waiting"){machine.rotation.y=look.x*.055;machine.rotation.x=look.y*.018}else{machine.rotation.x*=.9;machine.rotation.y*=.9}renderer.render(scene,camera)}requestAnimationFrame(animate);
