import * as THREE from "./vendor/three.module.min.js";
import { CHARACTERS, avatarStyle } from "./characters.js";
import { Store } from "./store.js";

const $=s=>document.querySelector(s), statusEl=$("#status"), spinButton=$("#spin"), soundButton=$("#sound"), exitButton=$("#exit"), collectionButton=$("#collectionButton"), reveal=$("#reveal"), collection=$("#collection");
const embedded=self!==top, THEME="./assets/audio/glitch-park-theme.mp3";
let soundEnabled=true, themeAudio, audioContext, phase="waiting", phaseTime=0, results=[0,0,0], targets=[0,0,0], stopped=[false,false,false], nextTick=[0,0,0], look={x:0,y:0,tx:0,ty:0},effectFlash=0,celebrationTime=0,coinTime=0,paylineTime=0;
Store.load();

function requestTheme(action,muted=false){
  if(embedded){ parent.postMessage({type:"glitch-park:music",action,track:"theme",url:new URL(THEME,location.href).href,muted},"*"); return; }
  themeAudio||=Object.assign(new Audio(THEME),{loop:true,volume:.27}); themeAudio.muted=muted;
  if(action==="play"&&!muted) themeAudio.play().catch(()=>{}); if(action==="pause") themeAudio.pause();
}
if(embedded){exitButton.hidden=false;exitButton.onclick=()=>parent.postMessage({type:"slots:exit"},"*");}
else requestTheme("play");
function beep(freq=440,duration=.08,volume=.05,type="sine"){
  if(!soundEnabled)return; audioContext||=new(window.AudioContext||window.webkitAudioContext)(); const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration);
}
function sfxCoin(){beep(980,.055,.065,"square");setTimeout(()=>beep(620,.1,.055,"triangle"),60)}
function sfxLever(){beep(115,.22,.075,"sawtooth");setTimeout(()=>beep(190,.12,.055,"square"),90)}
function sfxStop(index){beep(300+index*105,.13,.07,"square");setTimeout(()=>beep(610+index*90,.07,.045,"triangle"),55)}
function sfxResult(jackpot){if(jackpot)[523,659,784,1047].forEach((f,i)=>setTimeout(()=>beep(f,.24,.075,i===3?"square":"triangle"),i*125));else[392,523,659].forEach((f,i)=>setTimeout(()=>beep(f,.16,.055,"triangle"),i*90))}
soundButton.onclick=()=>{soundEnabled=!soundEnabled;soundButton.textContent=`聲音：${soundEnabled?"開":"關"}`;soundButton.setAttribute("aria-pressed",String(!soundEnabled));requestTheme("mute",!soundEnabled);if(soundEnabled){requestTheme("play");beep(660);}};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x211332);scene.fog=new THREE.Fog(0x211332,12,30);
const camera=new THREE.PerspectiveCamera(42,1,.1,50),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.body.prepend(renderer.domElement);
const mat=(color,rough=.45,metal=.05,emissive=0,intensity=0)=>new THREE.MeshStandardMaterial({color,roughness:rough,metalness:metal,emissive,emissiveIntensity:intensity});
const box=(w,h,d,m,x,y,z,p=scene)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o};
scene.add(new THREE.HemisphereLight(0xbca8e6,0x352044,2.35));const key=new THREE.SpotLight(0xf0e8ff,31,18,.62,.58,1.65);key.position.set(2.8,8,7);key.target.position.set(0,2.4,0);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key,key.target);
for(const [x,c] of [[-4,0x69eee0],[4,0xff69c3]]){const p=new THREE.PointLight(c,12,9,2);p.position.set(x,2.2,2);scene.add(p)}
// 有實體色塊與反光的棋盤地板；不再用接近純黑的材質只畫幾條格線。
const floorCanvas=document.createElement("canvas");floorCanvas.width=floorCanvas.height=256;const fx=floorCanvas.getContext("2d");for(let y=0;y<4;y++)for(let x=0;x<4;x++){fx.fillStyle=(x+y)%2?"#4b3367":"#302044";fx.fillRect(x*64,y*64,64,64);fx.strokeStyle="rgba(105,238,224,.22)";fx.strokeRect(x*64,y*64,64,64)}const floorTexture=new THREE.CanvasTexture(floorCanvas);floorTexture.colorSpace=THREE.SRGBColorSpace;floorTexture.wrapS=floorTexture.wrapT=THREE.RepeatWrapping;floorTexture.repeat.set(5,5);const floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.MeshStandardMaterial({map:floorTexture,color:0xd9c9ec,roughness:.48,metalness:.08}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
// 放大的實體後牆完整包住鏡頭；浮雕紋理、燈框與裝飾機台讓空間接近其他遊樂園場景。
const wallCanvas=document.createElement("canvas");wallCanvas.width=512;wallCanvas.height=256;const wx=wallCanvas.getContext("2d"),wg=wx.createLinearGradient(0,0,512,256);wg.addColorStop(0,"#321d4b");wg.addColorStop(.5,"#51306d");wg.addColorStop(1,"#26163d");wx.fillStyle=wg;wx.fillRect(0,0,512,256);wx.strokeStyle="rgba(255,255,255,.075)";wx.lineWidth=3;for(let x=-256;x<768;x+=64){wx.beginPath();wx.moveTo(x,0);wx.lineTo(x+256,256);wx.stroke()}for(let y=28;y<256;y+=56){wx.strokeStyle="rgba(105,238,224,.055)";wx.beginPath();wx.moveTo(0,y);wx.lineTo(512,y);wx.stroke()}const wallTexture=new THREE.CanvasTexture(wallCanvas);wallTexture.colorSpace=THREE.SRGBColorSpace;wallTexture.wrapS=wallTexture.wrapT=THREE.RepeatWrapping;wallTexture.repeat.set(4,2);box(30,12,.3,new THREE.MeshStandardMaterial({map:wallTexture,color:0xb899cb,roughness:.8,bumpMap:wallTexture,bumpScale:.055}),0,4.7,-5.4);box(26,.13,.12,mat(0x69eee0,.2,.1,0x69eee0,3),0,7.2,-5.18);box(26,.08,.1,mat(0xff72c5,.2,.1,0xff72c5,3),0,.62,-5.17);
const backScreens=[];for(const x of [-8,-6,-4,4,6,8]){const c=x%4===0?0x69eee0:0xff72c5;box(1.25,3.35,1.22,mat(0x392451,.45,.12),x,1.68,-3.75);const screen=box(.92,1.45,.08,mat(0x161020,.3,.05,0x35204f,.6),x,2.15,-3.09);backScreens.push(screen);box(1.02,.45,.09,mat(c,.22,.08,c,2.8),x,3.08,-3.08);box(.78,.1,.12,mat(c,.2,.1,c,3.2),x,.3,-3.06);const lamp=new THREE.PointLight(c,3.8,3.4,2);lamp.position.set(x,2.7,-2.7);scene.add(lamp)}
for(const x of [-8.8,-7.2,-5.6,-4,4,5.6,7.2,8.8]){const bulb=new THREE.PointLight(x%3?0xffd7a1:0x9cfff4,1.7,2.4,2);bulb.position.set(x,5.8,-4.7);scene.add(bulb);const globe=new THREE.Mesh(new THREE.SphereGeometry(.09,12,8),mat(0xffffff,.2,0,0xffffff,3));globe.position.copy(bulb.position);scene.add(globe)}
const machine=new THREE.Group();scene.add(machine);
// 圓肩、收腰的厚機殼才有拉霸機輪廓，正面再分成轉輪、操作與出幣三區。
const cabinetShape=new THREE.Shape();cabinetShape.moveTo(-2.18,0);cabinetShape.lineTo(-2.18,4.78);cabinetShape.quadraticCurveTo(-2.18,5.58,-1.38,5.65);cabinetShape.lineTo(1.38,5.65);cabinetShape.quadraticCurveTo(2.18,5.58,2.18,4.78);cabinetShape.lineTo(2.18,0);cabinetShape.closePath();const cabinetBody=new THREE.Mesh(new THREE.ExtrudeGeometry(cabinetShape,{depth:2,bevelEnabled:true,bevelSize:.12,bevelThickness:.12,bevelSegments:4}),mat(0x704a8e,.34,.25,0x311b48,.42));cabinetBody.position.z=-1.08;cabinetBody.castShadow=cabinetBody.receiveShadow=true;machine.add(cabinetBody);
box(4.05,4.65,.12,mat(0x684486,.42,.12,0x392250,.45),0,2.55,1.08,machine);
box(.13,4.5,.15,mat(0x69eee0,.2,.2,0x69eee0,3.4),-1.96,2.54,1.2,machine);
box(.13,4.5,.15,mat(0xff72c5,.2,.2,0xff72c5,3.4),1.96,2.54,1.2,machine);
box(4.32,1.05,.16,mat(0x20122e,.25,.1,0xff72c5,2.7),0,5.08,1.2,machine);box(4.02,.76,.08,mat(0x171022,.3,.1),0,5.08,1.31,machine);
const signCanvas=document.createElement("canvas");signCanvas.width=900;signCanvas.height=180;const sx=signCanvas.getContext("2d");sx.fillStyle="#211333";sx.fillRect(0,0,900,180);sx.strokeStyle="#69eee0";sx.lineWidth=12;sx.strokeRect(10,10,880,160);sx.textAlign="center";sx.fillStyle="#ffd36e";sx.font="900 86px system-ui";sx.fillText("GLITCH 777",450,108);sx.fillStyle="#f8f4ff";sx.font="500 24px system-ui";sx.fillText("格莉奇遊樂園・幸運拉霸",450,148);const signTex=new THREE.CanvasTexture(signCanvas);signTex.colorSpace=THREE.SRGBColorSpace;const sign=new THREE.Mesh(new THREE.PlaneGeometry(3.9,.78),new THREE.MeshBasicMaterial({map:signTex,toneMapped:false}));sign.position.set(0,5.08,1.405);machine.add(sign);
box(3.72,2.12,.3,mat(0x1d102b,.25,.2,0x12091e,.42),0,3.48,1.18,machine);box(3.9,2.3,.12,mat(0xffd5ed,.28,.15,0xff72c5,.6),0,3.48,1.12,machine);box(3.64,2.04,.14,mat(0x211331,.25,.12),0,3.48,1.25,machine);const atlas=await new THREE.TextureLoader().loadAsync("./assets/avatar-atlas.webp");atlas.colorSpace=THREE.SRGBColorSpace;atlas.wrapS=atlas.wrapT=THREE.RepeatWrapping;
function setMapIndex(map,index){index=(index+CHARACTERS.length)%CHARACTERS.length;map.offset.set(index%4*.25,Math.floor(index/4)?0:.5);map.needsUpdate=true}
function reelMaterial(index,opacity=1){const map=atlas.clone();map.needsUpdate=true;map.repeat.set(.25,.5);setMapIndex(map,index);return new THREE.MeshBasicMaterial({map,toneMapped:false,transparent:opacity<1,opacity})}
function setSymbol(reel,index){for(const [offset,cell] of reel.userData.cells.entries())setMapIndex(cell.material.map,index+offset-1);results[reels.indexOf(reel)]=index;}
const reels=[];for(let i=0;i<3;i++){const x=(i-1)*1.14;box(1.02,1.86,.1,mat(0xd9cae9,.35,.18),x,3.48,1.37,machine);box(.87,1.68,.05,mat(0x171020,.3),x,3.48,1.44,machine);const cells=[];for(const [j,y] of [2.92,3.48,4.04].entries()){const size=j===1?.82:.48,cell=new THREE.Mesh(new THREE.PlaneGeometry(size,size),reelMaterial(i+j-1,j===1?1:.46));cell.position.set(x,y,1.5);machine.add(cell);cells.push(cell)}const reel=cells[1];reel.userData.cells=cells;reels.push(reel);setSymbol(reel,i)}
// 背景機台與牆上海報都共用同一張角色 atlas，維持正方形比例而不拉伸。
for(const [i,screen] of backScreens.entries()){const m=reelMaterial((i+1)%7,.92);screen.material=m;screen.scale.y=.64}
for(const [i,x] of [-7.5,-5.5,5.5,7.5].entries()){box(1.34,1.34,.12,mat(i%2?0xff72c5:0x69eee0,.28,.12,i%2?0xff72c5:0x69eee0,1.5),x,5.35,-5.05);const poster=new THREE.Mesh(new THREE.PlaneGeometry(1.16,1.16),reelMaterial([3,6,0,1][i]));poster.position.set(x,5.35,-4.97);scene.add(poster)}
const payline=box(3.55,.055,.045,mat(0xffd36e,.2,.2,0xffd36e,5),0,3.48,1.56,machine);payline.visible=false;
function labelPlane(text,width,height,color=0xffd36e){const c=document.createElement("canvas");c.width=512;c.height=160;const x=c.getContext("2d");x.fillStyle="#211331";x.fillRect(0,0,c.width,c.height);x.strokeStyle=`#${color.toString(16).padStart(6,"0")}`;x.lineWidth=8;x.strokeRect(6,6,c.width-12,c.height-12);x.fillStyle="#fff";x.font="700 58px system-ui";x.textAlign="center";x.textBaseline="middle";x.fillText(text,c.width/2,c.height/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const p=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:t,toneMapped:false}));machine.add(p);return p}
box(3.62,.76,.48,mat(0x4a2d67,.32,.22,0x2a173e,.55),0,2.02,1.13,machine);
const coinLabel=labelPlane("投幣孔  COIN",1.18,.36);coinLabel.position.set(-1.05,2.16,1.4);
const coin=box(.52,.58,.13,mat(0x171022,.25,.5),-1.05,1.72,1.4,machine);coin.userData.action="coin";box(.08,.34,.04,mat(0xffd36e,.2,.5,0xffd36e,3),-1.05,1.72,1.49,machine);
const coinToken=new THREE.Mesh(new THREE.CircleGeometry(.19,28),new THREE.MeshBasicMaterial({color:0xffd36e,toneMapped:false}));coinToken.visible=false;machine.add(coinToken);
const jackpotLabel=labelPlane("JACKPOT",1.5,.46,0x69eee0);jackpotLabel.position.set(.68,1.92,1.4);
const mount=new THREE.Mesh(new THREE.CylinderGeometry(.28,.32,.48,20),mat(0xbbb7c7,.2,.75));mount.rotation.z=Math.PI/2;mount.position.set(2.24,2.5,.45);machine.add(mount);const lever=new THREE.Group();lever.position.set(2.42,2.5,.48);machine.add(lever);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.075,.085,1.25,14),mat(0xe9e6f0,.18,.75));stem.position.y=.58;lever.add(stem);const knob=new THREE.Mesh(new THREE.SphereGeometry(.25,24,18),mat(0xff6dbd,.22,.25,0xff6dbd,1.5));knob.position.y=1.22;lever.add(knob);knob.userData.action=stem.userData.action="spin";
// 下半部用真正凹入的出幣口收尾，兩側霓虹是裝飾，不再用整排直條代替機構。
box(3.55,1.26,.12,mat(0x51336f,.42,.16,0x2d1942,.5),0,.88,1.22,machine);box(1.72,.58,.16,mat(0x150c20,.24,.18),0,.72,1.34,machine);box(1.42,.25,.08,mat(0x08050d,.3,.1),0,.72,1.47,machine);box(1.55,.06,.08,mat(0xffd36e,.2,.1,0xffd36e,2.8),0,.49,1.48,machine);for(const [x,c] of [[-1.63,0x69eee0],[1.63,0xff72c5]])box(.09,.92,.08,mat(c,.2,.1,c,3),x,.88,1.38,machine);
const floorGlow=new THREE.PointLight(0x9b6de1,5.5,5,2);floorGlow.position.set(0,.35,1.1);machine.add(floorGlow);
// 招牌跑馬燈與得獎碎光，全部共用幾何與材質，不增加圖片下載。
const chaseBulbs=[];for(let i=0;i<16;i++){const x=-1.75+i/15*3.5,c=i%2?0xff72c5:0x69eee0,m=mat(c,.2,0,c,.5),bulb=new THREE.Mesh(new THREE.SphereGeometry(.035,8,6),m);bulb.position.set(x,i%2?5.43:4.72,1.48);machine.add(bulb);chaseBulbs.push(m)}
const effectLight=new THREE.PointLight(0xffd36e,0,7,2);effectLight.position.set(0,3.2,2.5);scene.add(effectLight);
const confettiCount=72,confettiPositions=new Float32Array(confettiCount*3),confettiColors=new Float32Array(confettiCount*3),confettiVelocity=[];const confettiGeometry=new THREE.BufferGeometry();confettiGeometry.setAttribute("position",new THREE.BufferAttribute(confettiPositions,3));confettiGeometry.setAttribute("color",new THREE.BufferAttribute(confettiColors,3));const confetti=new THREE.Points(confettiGeometry,new THREE.PointsMaterial({size:.075,vertexColors:true,transparent:true,opacity:.95,depthWrite:false}));confetti.visible=false;scene.add(confetti);
function burstConfetti(){const palette=[new THREE.Color(0x69eee0),new THREE.Color(0xff72c5),new THREE.Color(0xffd36e),new THREE.Color(0xbda7ff)];for(let i=0;i<confettiCount;i++){confettiPositions[i*3]=(Math.random()-.5)*2.2;confettiPositions[i*3+1]=3.4+Math.random()*.8;confettiPositions[i*3+2]=1.8+Math.random()*.5;const color=palette[i%palette.length];confettiColors.set([color.r,color.g,color.b],i*3);confettiVelocity[i]={x:(Math.random()-.5)*1.8,y:1.2+Math.random()*2,z:(Math.random()-.5)*.7}}confettiGeometry.attributes.position.needsUpdate=confettiGeometry.attributes.color.needsUpdate=true;confetti.visible=true;celebrationTime=2.8}

function resize(){const w=innerWidth,h=innerHeight,tall=h/w>1.22;renderer.setSize(w,h);camera.aspect=w/h;camera.fov=tall?48:40;camera.position.set(0,tall?3.45:3.55,tall?11.25:11.65);camera.lookAt(0,tall?2.75:2.62,-.15);camera.updateProjectionMatrix()}addEventListener("resize",resize);resize();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener("pointerdown",e=>{requestTheme("play",!soundEnabled);pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(machine.children,true).find(h=>h.object.userData.action);if(hit?.object.userData.action==="coin")insertCoin();if(hit?.object.userData.action==="spin")spin();});renderer.domElement.addEventListener("pointermove",e=>{if(phase!=="waiting")return;look.tx=e.clientX/innerWidth*2-1;look.ty=e.clientY/innerHeight*2-1});
function insertCoin(){if(phase!=="waiting")return;phase="ready";statusEl.innerHTML="代幣投入完成，<b>拉下右側把手</b>。";spinButton.textContent="拉下把手";spinButton.classList.remove("prompt");coinTime=.72;coinToken.visible=true;effectFlash=.7;sfxCoin();}
function spin(){if(phase==="waiting"){insertCoin();return}if(phase!=="ready")return;phase="spinning";phaseTime=0;stopped=[false,false,false];nextTick=[0,0,0];const hero=Math.floor(Math.random()*7),jackpot=Math.random()<.23;targets=jackpot?[hero,hero,hero]:[Math.floor(Math.random()*7),hero,Math.floor(Math.random()*7)];if(!jackpot&&targets[0]===hero&&targets[2]===hero)targets[2]=(hero+1)%7;statusEl.textContent="轉輪正在尋找今天的幸運角色……";spinButton.disabled=true;lever.rotation.z=-.52;sfxLever();}
spinButton.onclick=()=>phase==="waiting"?insertCoin():spin();addEventListener("keydown",e=>{if(e.key==="c"||e.key==="C")insertCoin();if(e.code==="Space"){e.preventDefault();phase==="waiting"?insertCoin():spin();}});
function finish(){const jackpot=targets.every(v=>v===targets[0]),hero=CHARACTERS[targets[1]];Store.finish(hero.id,jackpot);renderCollection();statusEl.innerHTML=jackpot?`<b>777 JACKPOT！</b>${hero.name} 已加入收藏。`:`本局幸運角色是 <b>${hero.name}</b>。`;reveal.innerHTML=`<div class="card"><div class="eyebrow">${jackpot?"777 JACKPOT":"本局幸運角色"}</div><div class="bigAvatar"><span class="avatar" style="${avatarStyle(targets[1])}"></span></div><h2>${hero.name}</h2><p>「${hero.line}」</p><button>再玩一次</button></div>`;reveal.hidden=true;reveal.querySelector("button").onclick=reset;effectLight.color.setHex(hero.color);effectFlash=jackpot?2.4:1.1;paylineTime=jackpot?1.15:0;if(jackpot)burstConfetti();sfxResult(jackpot);phase="showing";setTimeout(()=>{if(phase==="showing")reveal.hidden=false},jackpot?620:120)}
function reset(){reveal.hidden=true;phase="waiting";phaseTime=0;spinButton.disabled=false;spinButton.textContent="投幣";spinButton.classList.add("prompt");statusEl.textContent="請先投入代幣。";lever.rotation.z=0;payline.visible=false;}
function renderCollection(){collectionButton.innerHTML=CHARACTERS.map((c,i)=>Store.data.owned.includes(c.id)?`<span class="slot has"><span class="avatar" style="${avatarStyle(i)}"></span></span>`:`<span class="slot">？</span>`).join("")}
function openCollection(){collection.innerHTML=`<div class="card"><div class="collectionHead"><span>777 中獎收藏（${Store.data.owned.length}/7）</span><button>關閉</button></div>${CHARACTERS.map((c,i)=>`<div class="row"><span class="mini"><span class="avatar" style="${avatarStyle(i)}"></span></span><div><b>${c.name}</b><br><small>${Store.data.owned.includes(c.id)?"JACKPOT 已收藏":"尚未轉到三個相同圖案"}</small></div></div>`).join("")}</div>`;collection.hidden=false;collection.querySelector("button").onclick=()=>collection.hidden=true}
collectionButton.onclick=openCollection;collectionButton.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openCollection()}};renderCollection();spinButton.classList.add("prompt");
let last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05),time=now/1000;last=now;phaseTime+=dt;if(phase==="spinning"){for(let i=0;i<3;i++){if(stopped[i])continue;if(phaseTime>nextTick[i]){setSymbol(reels[i],(results[i]+1)%7);nextTick[i]=phaseTime+.065;beep(205+i*38,.035,.026,"square")}if(phaseTime>1.25+i*.52){setSymbol(reels[i],targets[i]);stopped[i]=true;effectFlash=.85;sfxStop(i)}}if(stopped.every(Boolean)){phase="settling";setTimeout(finish,260)}}effectFlash=Math.max(0,effectFlash-dt*1.5);effectLight.intensity=effectFlash*10;if(coinTime>0){coinTime-=dt;const p=1-Math.max(0,coinTime)/.72,s=1-p*.38;coinToken.position.set(-1.05,2.75-p*1.03,1.75+p*.04);coinToken.rotation.z+=dt*5;coinToken.scale.set((.28+.72*Math.abs(Math.cos(p*Math.PI*4)))*s,s,1);if(coinTime<=0)coinToken.visible=false}if(paylineTime>0){paylineTime-=dt;payline.visible=Math.floor(paylineTime*12)%2===0;payline.scale.x=.35+(1-Math.min(1,paylineTime))*.65;if(paylineTime<=0)payline.visible=false}for(let i=0;i<chaseBulbs.length;i++)chaseBulbs[i].emissiveIntensity=phase==="spinning"&&((i+Math.floor(time*15))%6<2)?4.5:.65+effectFlash*1.8;if(celebrationTime>0){celebrationTime-=dt;const a=confettiGeometry.attributes.position.array;for(let i=0;i<confettiCount;i++){const v=confettiVelocity[i];a[i*3]+=v.x*dt;a[i*3+1]+=v.y*dt;a[i*3+2]+=v.z*dt;v.y-=3.2*dt}confettiGeometry.attributes.position.needsUpdate=true;confetti.material.opacity=Math.min(1,celebrationTime);if(celebrationTime<=0)confetti.visible=false}look.x+=(look.tx-look.x)*Math.min(dt*2.5,1);look.y+=(look.ty-look.y)*Math.min(dt*2.5,1);if(phase==="waiting"){machine.rotation.y=look.x*.055;machine.rotation.x=look.y*.018}else{machine.rotation.x*=.9;machine.rotation.y*=.9}machine.position.x=phase==="spinning"?Math.sin(time*42)*.008:0;machine.position.y=phase==="spinning"?Math.sin(time*31)*.01:0;machine.rotation.z=phase==="spinning"?Math.sin(time*36)*.002:0;renderer.render(scene,camera)}requestAnimationFrame(animate);
